### ISSUE TITLE
PHP Fatal error:  During inheritance of XMLReader

### ISSUE THREAD

**Issue by peter-neumann-dev** [pagemachine/svconnector_xls#60]
After upgrading from TYPO3 v10 to v11 and PHP 7.4 to 8.0 the import crashes both from CLI and Backend:

```
PHP Fatal error:  During inheritance of XMLReader: Uncaught TYPO3\CMS\Core\Error\Exception: PHP Runtime Deprecation Notice: Return type of Box\Spout\Reader\Wrapper\XMLReader::read() should either be compatible with XMLReader::read(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/box/spout/src/Spout/Reader/Wrapper/XMLReader.php line 86 in /var/www/html/public/typo3/sysext/core/Classes/Error/ErrorHandler.php:137
Stack trace:
#0 /var/www/html/vendor/box/spout/src/Spout/Reader/Wrapper/XMLReader.php(10): TYPO3\CMS\Core\Error\ErrorHandler->handleError(8192, 'Return type of ...', '/var/www/html/v...', 86)
#1 /var/www/html/vendor/composer/ClassLoader.php(571): include('/var/www/html/v...')
#2 /var/www/html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/html/v...')
#3 /var/www/html/vendor/box/spout/src/Spout/Reader/XLSX/Creator/InternalEntityFactory.php(151): Composer\Autoload\ClassLoader->loadClass('Box\\Spout\\Reade...')
#4 /var/www/html/vendor/box/spout/src/Spout/Reader/XLSX/Manager/WorkbookRelationshipsManager.php(120): Box\Spout\Reader\XLSX\Creator\InternalEntityFactory->createXMLReader()
#5 /var/www/html/vendor/box/spout/src/Spout/Reader/XLSX/Manager/WorkbookRelationshipsManager.php(74): Box\Spout\Reader\XLSX\Manager\WorkbookRelationshipsManager->getWorkbookRelationships()
#6 /var/www/html/vendor/box/spout/src/Spout/Reader/XLSX/Manager/SharedStringsManager.php(83): Box\Spout\Reader\XLSX\Manager\WorkbookRelationshipsManager->hasSharedStringsXMLFile()
#7 /var/www/html/vendor/box/spout/src/Spout/Reader/XLSX/Reader.php(90): Box\Spout\Reader\XLSX\Manager\SharedStringsManager->hasSharedStrings()
#8 /var/www/html/vendor/box/spout/src/Spout/Reader/ReaderAbstract.php(127): Box\Spout\Reader\XLSX\Reader->openReader('/var/www/html/p...')
#9 /var/www/html/public/typo3conf/ext/svconnector_xls/Classes/Service/XlsxConnector.php(43): Box\Spout\Reader\ReaderAbstract->open('/var/www/html/p...')
#10 /var/www/html/public/typo3conf/ext/svconnector_xls/Classes/Service/AbstractConnector.php(50): Pagemachine\SvconnectorXls\Service\XlsxConnector->query(Array)
#11 /var/www/html/public/typo3conf/ext/external_import/Classes/Step/ReadDataStep.php(137): Pagemachine\SvconnectorXls\Service\AbstractConnector->fetchArray(Array)
#12 /var/www/html/public/typo3conf/ext/external_import/Classes/Importer.php(389): Cobweb\ExternalImport\Step\ReadDataStep->run()
#13 /var/www/html/public/typo3conf/ext/external_import/Classes/Importer.php(251): Cobweb\ExternalImport\Importer->runSteps(Object(Cobweb\ExternalImport\Domain\Model\Data))
#14 /var/www/html/public/typo3conf/ext/external_import/Classes/Command/ImportCommand.php(242): Cobweb\ExternalImport\Importer->synchronize('fe_users', 0)
#15 /var/www/html/public/typo3conf/ext/external_import/Classes/Command/ImportCommand.php(164): Cobweb\ExternalImport\Command\ImportCommand->runSynchronization(Array)
#16 /var/www/html/vendor/symfony/console/Command/Command.php(298): Cobweb\ExternalImport\Command\ImportCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Cobweb\ExternalImport\Command\ImportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/public/typo3/sysext/core/Classes/Console/CommandApplication.php(119): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/typo3/cms-cli/typo3(23): TYPO3\CMS\Core\Console\CommandApplication->run()
#22 /var/www/html/vendor/typo3/cms-cli/typo3(24): {closure}()
#23 /var/www/html/vendor/bin/typo3(120): include('/var/www/html/v...')
#24 {main} in /var/www/html/vendor/box/spout/src/Spout/Reader/Wrapper/XMLReader.php on line 10
```

Before it worked totally fine, since I am using still the same version of `external_import` and `svconnector`, I guess it has to related to PHP or v11 🤔

**Comment by peter-neumann-dev** [comment]
Updates: 

I now have deployed the TYPO3 update to staging and production servers. It looks like this issue only exists on DDEV. On both servers (different hosters) the import succeeds after patching other undefined array keys warnings #62

I guess maybe it happens because of PHP 8.1 and its different configuration under DDEV because staging and production environments it's working now. I created a post about this in [DDEV discord](https://discord.com/channels/664580571770388500/1041018721684168814), perhaps someone has an idea.

**Comment by peter-neumann-dev** [comment]
It turns out that it only happens in TYPO3 Debug Mode (`'exceptionalErrors' => 12290`) in lower debug levels like Production Mode (`'exceptionalErrors' => 4096`) it's working again.

If I downgrade from PHP 8.1 to PHP 8.0 it is working with debug mode, so it seems to be an issue with PHP 8.1 and TYPO3 Debug Mode (`'exceptionalErrors' => 12290`)

**Comment by mbrodala** [comment]
This seems to be caused by `box/spout` which was abandoned a while ago anyways: https://packagist.org/packages/box/spout

So we'll need to replace that first, which will very likely also fix this issue.

**Comment by mbrodala** [comment]
Short note: we need to check if memory usage is still an issue with XLSX, see https://github.com/pagemachine/svconnector_xls/pull/5
